version: '3.8'

services:
  name_scandi_bot:
    # container_name: scandi-bot 
    build: .
    image: name_scandi_bot
    environment:
      - TOKEN_TG=${TOKEN_TG}
      - OPENAI_KEY=${OPENAI_KEY}
      - ADMIN_ID=${ADMIN_ID}
      - TZ=Europe/Moscow
      - PYTHONDONTWRITEBYTECODE=1   # не писать __pycache__/*.pyc (важно при read_only)
      - TMPDIR=/tmp                 # чтобы все временные файлы шли в tmpfs
      - PYTHONUNBUFFERED=1          # мгновенный вывод логов
    
    # не запускать под root (подставьте свои uid:gid, напр. 1000:1000)
    user: "1000:1000"

    # защищаем корневую ФС, разрешаем запись только туда, где нужно
    read_only: true
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
    tmpfs:
      - /tmp

    # ротация логов, чтобы не разрослись
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    # аккуратное завершение Python-процесса
    stop_signal: SIGINT
    stop_grace_period: 20s

    # маленький init, чтобы зомби-процессы не копились
    init: true

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    restart: unless-stopped