version: '3.8'

services:
  name_scandi_bot:
    container_name: scandi-bot 
    build: .
    image: name_scandi_bot
    environment:
      - TOKEN_TG=${TOKEN_TG}
      - OPENAI_KEY=${OPENAI_KEY}
      - ADMIN_ID=${ADMIN_ID}
      - TZ=Europe/Moscow

    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

    # ротация логов, чтобы не разрослись
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    # аккуратное завершение Python-процесса
    stop_signal: SIGINT
    stop_grace_period: 20s

    # маленький init, чтобы зомби-процессы не копились
    init: true

    restart: unless-stopped